Traceback (most recent call last):
  File "/mnt/nfs/nrdata02-users-data/luciano/script/ABC-SBI/examples/Gauss-Gauss/Gauss_Gauss_Muli_known_sigma/cluster_pattern_multigauss.py", line 11, in <module>
    from functions.plots import plot_metric_for_many_datasets 
  File "/mnt/nfs/nrdata02-users-data/luciano/script/ABC-SBI/functions/plots.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/matplotlib/figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/matplotlib/projections/__init__.py", line 55, in <module>
    from .. import axes, _docstring
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/matplotlib/axes/__init__.py", line 2, in <module>
    from ._axes import *
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 11, in <module>
    import matplotlib.category  # Register category unit converter as side effect.
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/matplotlib/category.py", line 14, in <module>
    import dateutil.parser
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/home/users/luciano/miniconda3/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 42, in <module>
    import six
ModuleNotFoundError: No module named 'six'
